name: IMS - SFTP Action
branding:
  icon: satellite
  color: orange
description: |
  This GitHub Action allows you to upload files recursively using FTP/SFTP to an IMS network server.
  It reads the specified local directory and uploads its contents to the provided SFTP server URL.
author: ims-network
runs:
  using: 'composite'
  steps:
    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp
      shell: bash

    - name: Upload files using SFTP
      run: |
        cd ${{ inputs.local-directory }}
        # Extract the username, password, and server URL from the inputs.url
        USERNAME=$(echo ${{ inputs.url }} | cut -d/ -f3 | cut -d: -f1)
        PASSWORD=$(echo ${{ inputs.url }} | cut -d/ -f3 | cut -d: -f2 | cut -d@ -f1)
        SERVER=$(echo ${{ inputs.url }} | cut -d/ -f3 | cut -d@ -f2)
        # Use lftp to upload the files
        lftp -u $USERNAME,$PASSWORD sftp://$SERVER -e "
          mirror --reverse --delete --verbose
          quit
        "
      shell: bash
    - name: Clean up temporary files
      # Clean up the temporary script file
      run: rm /tmp/commands.ftp
      shell: bash
inputs:
  url:
    description: 'URL to the SFTP server. Example: sftp://USERNAME:PASSWORD@example.com/remote-directory'
    required: true
  local-directory:
    description: 'The directory that should be uploaded'
    required: true
