name: IMS - Network
# Update the branding as per your preference
branding:
  icon: satellite
  color: orange
description: |
  This GitHub Action allows you to upload files recursively using FTP/SFTP to an IMS network server.
  It reads the specified local directory and uploads its contents to the provided SFTP server URL.
author: ims-network
runs:
  using: 'composite'
  steps:
    - name: Set up Git environment
      # You can set up git config and credentials here if needed.
      # For example, you can configure git user.name and user.email.
      run: git config --global user.name 'GitHub Action' && git config --global user.email 'action@github.com'
      shell: bash
    - name: Upload files using SFTP
      run: |
        cd ${{ github.event.inputs.localdir }}
        # Create a temporary script for sftp commands
        echo "
          $(find . -type d | sed -e 's/^/mkdir /;')
          put -r .
          exit
        " > /tmp/commands.ftp
        # Run sftp command with input from the script file
        sftp ${{ github.event.inputs.url }} < /tmp/commands.ftp
      shell: bash
    - name: Clean up temporary files
      # Clean up the temporary script file
      run: rm /tmp/commands.ftp
      shell: bash
inputs:
  url:
    description: 'URL to the SFTP server. Example: sftp://USERNAME:PASSWORD@example.com/remote-directory'
    required: true
  localdir:
    description: 'The directory that should be uploaded'
    required: true
