name: IMS - SFTP Action
branding:
  icon: server
  color: orange
description: |
  This GitHub Action allows you to upload files recursively using FTP/SFTP to an IMS network server.
  It reads the specified local directory and uploads its contents to the provided SFTP server URL.
author: ims-network
inputs:
  username:
    description: 'Username for the SFTP server.'
    required: true
  password:
    description: 'Password for the SFTP server.'
    required: true
  server:
    description: 'SFTP server address. Example: example.com'
    required: true
  port:
    description: 'SFTP server port.'
    required: true
  remote-directory:
    description: 'Remote directory on the SFTP server to upload files to.'
    required: true
  local-directory:
    description: 'The directory that should be uploaded.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      run: |
        echo "INPUT_USERNAME=${{ inputs.username }}" >> $GITHUB_ENV
        echo "INPUT_PASSWORD=${{ inputs.password }}" >> $GITHUB_ENV
        echo "INPUT_SERVER=${{ inputs.server }}" >> $GITHUB_ENV
        echo "INPUT_PORT=${{ inputs.port }}" >> $GITHUB_ENV
        echo "INPUT_REMOTE_DIRECTORY=${{ inputs.remote-directory }}" >> $GITHUB_ENV
        echo "INPUT_LOCAL_DIRECTORY=${{ inputs.local-directory }}" >> $GITHUB_ENV

    - name: Upload files using SFTP
      run: |
        # Debugging line
        echo "Constructed URL: sftp://$INPUT_SERVER:$INPUT_PORT/$INPUT_REMOTE_DIRECTORY/$(basename $INPUT_LOCAL_DIRECTORY)"
        # Use curl to upload the files
        find $INPUT_LOCAL_DIRECTORY -type f -exec bash -c 'curl -k -u $INPUT_USERNAME:$INPUT_PASSWORD --disable-epsv --ftp-method nocwd -T {} sftp://$INPUT_SERVER:$INPUT_PORT/$INPUT_REMOTE_DIRECTORY/$(basename {})' \;
      shell: bash
