name: IMS - SFTP Action
branding:
  icon: satellite
  color: orange
description: |
  This GitHub Action allows you to upload files recursively using FTP/SFTP to an IMS network server.
  It reads the specified local directory and uploads its contents to the provided SFTP server URL.
author: ims-network
runs:
  using: 'composite'
  steps:
    - name: Upload files using SFTP
      run: |
        cd ${{ inputs.local-directory }}
        # Use curl to upload the files
        find . -type f -exec curl -u ${{ inputs.username }}:${{ inputs.password }} --disable-epsv --ftp-method nocwd -T {} sftp://${{ inputs.server }}/${{ inputs.remote-directory }}/{} \;
      shell: bash
inputs:
  username:
    description: 'Username for the SFTP server.'
    required: true
  password:
    description: 'Password for the SFTP server.'
    required: true
  server:
    description: 'SFTP server address. Example: example.com'
    required: true
  remote-directory:
    description: 'Remote directory on the SFTP server to upload files to.'
    required: true
  local-directory:
    description: 'The directory that should be uploaded.'
    required: true
