name: Test IMS - Network Action
on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  test_sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SFTP server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          echo 'PasswordAuthentication yes' | sudo tee -a /etc/ssh/sshd_config
          sudo systemctl start sshd
          mkdir -p ~/.ssh
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts
          sudo useradd -m testing
          echo "testing:testing" | sudo chpasswd
          sudo mkdir /home/testing/sftp
          sudo chown testing:testing /home/testing/sftp
          echo 'Match User testing
          PasswordAuthentication yes
          ChrootDirectory %h/sftp
          AllowTCPForwarding no
          X11Forwarding no
          ForceCommand internal-sftp' | sudo tee -a /etc/ssh/sshd_config
          sudo systemctl restart sshd

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Create SFTP Batch File
        run: echo "put test.txt" > sftp_batch.txt

      - name: Create file to be transferred
        run: echo "This is a test file" > test.txt

      - name: Create a directory and file to be transferred
        run: |
          mkdir test-local-dir
          echo "This is a test file" > test-local-dir/test.txt

      - name: Test IMS - Network Action
        uses: ims-network/ims-sftp-action@v1.2
        with:
          url: sftp://testing:testing@localhost:22/home/testing/sftp/
          local-directory: ./test-local-dir

      - name: Check if the file exists on the server
        run: |
          if sudo test -f /home/testing/sftp/test.txt; then
            echo "File exists"
          else
            echo "File does not exist"
            exit 1
          fi

      - name: Cleanup
        run: |
          sudo deluser --remove-home testing
          sudo sed -i '/Match User testing/,+5d' /etc/ssh/sshd_config
          sudo systemctl restart sshd
