name: Test IMS - Network Action
on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  test_sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Create file to be transferred
        run: |
          mkdir test-local-dir
          echo "This is a test file" > test-local-dir/test.txt

      - name: Test IMS - Network Action
        uses: ims-network/ims-sftp-action@vv2.3  # Replace with the correct path to your action repository
        with:
          username: testing
          password: testing
          server: 127.0.0.1
          port: 22  # Update with the correct port if needed
          remote-directory: /home/testing/sftp
          local-directory: ./test-local-dir

      # Add additional steps for checking if the file exists on the server or cleanup if needed
