name: Test IMS - Network Action
on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install netcat
      run: |
        sudo apt-get update
        sudo apt-get install -y netcat

    - name: Start SFTP server
      run: |
        ssh-keygen -t rsa -b 4096 -N "" -f /tmp/sftp_key
        docker run -d -p 2222:22 --name sftp-server -e SFTP_USERS="testuser:/tmp/sftp_key.pub" -e SFTP_ROOT=test-remote-dir \
        -v /tmp/sftp_key.pub:/tmp/sftp_key.pub atmoz/sftp

    - name: Wait for SFTP server to start
      run: |
        while ! nc -z localhost 2222; do sleep 1; done

    
    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/sftp_key -p 2222 testuser@localhost "echo SSH connection successful"

      

    - name: Create test files
      run: |
        mkdir -p test-local-dir
        echo "This is a test file" > test-local-dir/test-file.txt

    - name: Test IMS - Network Action
      uses: ims-network/ims-sftp-action@v1.2
      with:
        url: sftp://testuser:testpassword@localhost:2222/test-remote-dir/
        local-directory: ./test-local-dir/

    - name: List files on the remote server
      run: |
        ssh -p 2222 testuser@localhost ls -R /test-remote-dir
      shell: bash
