name: Test IMS - Network Action
on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start SFTP server
      run: |
        docker run -d -p 2222:22 -e SFTP_USER=testuser -e SFTP_PASSWORD=testpassword -e SFTP_DIRECTORY=test-remote-dir --name sftp-server atmoz/sftp

    - name: Wait for SFTP server to start
      run: |
        while ! nc -z localhost 2222; do sleep 1; done

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no -p 2222 testuser@localhost
      shell: bash

    - name: Create test files
      run: |
        mkdir -p test-local-dir
        echo "This is a test file" > test-local-dir/test-file.txt

    - name: Test IMS - Network Action
      uses: ims-network/ims-sftp-action@v1.2
      with:
        url: sftp://testuser:testpassword@localhost:2222/test-remote-dir/
        local-directory: ./test-local-dir/

    - name: List files on the remote server
      run: |
        ssh -p 2222 testuser@localhost ls -R /test-remote-dir
      shell: bash
